version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_docker
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker:/usr/libexec/docker
      - jenkins_home:/var/jenkins_home
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  jenkins_home:

 # Run these commands to verify and adjust permissions for docker.sock:
 # ls -lah /var/run/docker.sock  # Check the permissions of the Docker socket
 # chmod 666 /var/run/docker.sock  # Grant read/write access to the Docker socket